NFTopia-Foundation/nftopia

apps/frontend/app/layout.tsx
apps/frontend/components/Footer.tsx

feat:create footer component close #4

---

apps/frontend/components/explore-categories.tsx

feat: implemented explore

---

apps/frontend/components/main-hero.tsx

This PR introduces a visually engaging and responsive MainHero component for the Next.js project. The MainHero section serves as the primary landing area, featuring:
A headline with gradient text effects.
A descriptive paragraph to introduce the section.
Two call-to-action (CTA) buttons with hover effects.
Three statistics cards with hover animations and gradients.
A Vault component visualization on the right side.
The component is fully responsive and styled using Tailwind CSS, ensuring proper spacing, alignment, and adaptability across different screen sizes. Additionally, the component has been documented for future contributors.

Add Responsive MainHero Component with Vault Visualization & Statistics Cards

---

apps/frontend/app/page.tsx

Feat:Create Homepage Layout

---

apps/frontend/components/live-auctions.tsx

Implemented a LiveAuctions component displaying auction items in a responsive carousel.
Auto-rotates every 5 seconds with manual navigation via next/previous buttons.
Displays 4 items per page, with dynamic page indicators.
Includes live countdown timers, creator info, bid button, and responsive layout.
This closes #57

live auction component created

---

apps/backend/package.json
apps/backend/pnpm-lock.yaml
apps/backend/src/nftstorage/nftstorage.config.ts
apps/backend/src/nftstorage/nftstorage.module.ts
apps/backend/src/nftstorage/nftstorage.service.ts
apps/frontend/components/navbar.tsx
apps/frontend/pnpm-lock.yaml

- I implemented the NftStorageModule to provide NftStorageService in order to enhance upload of files to NFT.Storage IPFS storage platform.
close #45

feat: Implemented NFTStroge Moudle to provide NftStorageService

---

apps/frontend/app/marketplace/page.tsx

Description:
This commit adds a comprehensive NFT marketplace page to the NFTopia platform. The page is designed to align with the cosmic theme and includes the following sections:
Hero Section: A visually engaging header for the marketplace.
Live Auctions Carousel: Displays ongoing auctions dynamically.
Top Sellers Section: Highlights top-performing sellers.
Today's Picks Grid: Includes filtering functionality for curated NFTs.
Popular Collections Showcase: Displays trending NFT collections.
Create & Sell Guide: Offers users guidance on creating and selling NFTs.
Key features include:
Responsive design for mobile, tablet, and desktop.
Consistent dark theme with purple accents and cosmic/circuit backgrounds.
Optimized performance and proper SEO metadata.
Related Issue: Closes …

feat: implement NFT marketplace page with key sections

---

apps/frontend/components/Footer.tsx
apps/frontend/components/navbar.tsx
apps/frontend/components/top-sellers.tsx

Added navbar footer top-sellers

---

apps/frontend/app/page.tsx
apps/frontend/components/CollectionCard.tsx
apps/frontend/components/PopularCollection.tsx
apps/frontend/components/types/index.ts
apps/frontend/package-lock.json
apps/frontend/package.json
apps/frontend/types/index.ts
package-lock.json

This PR introduces the initial implementation of the `PopularCollection` component for the NFTopia Marketplace homepage (or relevant page). It includes:
-   `PopularCollection.tsx`: The main section component with header, "Explore More" link, and responsive grid layout.
-   `CollectionCard.tsx`: A reusable card component displaying collection details with a unique 3-image grid layout.
-   `types/index.ts`: Added `Collection` interface.
-   Basic "cosmic theme" styling with Tailwind CSS (dark backgrounds, purple accents).
-   Interactive hover effects (card lift, shadow) and focus states for accessibility.
-   Client-side like button functionality (`useState`) with visual feedback.
-   Placeholder SVG logo (`nftopia-03.svg`) used within the image grid via `next/image`.
-   Basic …

Implement Popular Collection Component

---

apps/backend/src/categories/categories.controller.spec.ts
apps/backend/src/categories/categories.controller.ts
apps/backend/src/categories/categories.module.ts
apps/backend/src/categories/categories.service.ts
apps/backend/src/categories/category.service.spec.ts
apps/backend/src/categories/dto/create-category.dto.ts
apps/backend/src/categories/dto/update-category.dto.ts
apps/backend/src/categories/entities/category.entity.ts

- Refactor the files in Categories Module to make sure the methods have defined return types.
- Wrote test for the controller and service classes. 
close #76

Fix: Refactored files under Categories Module to have Defined Return Types

---

on-chain/nftopia/src/lib.cairo

- Restructured the `/on-chain` folder for efficiency and clarity by having `/storage`, `/contracts`, `/interfaces`, `/modules`, `/utils`, and `/events` folders as children of `/src` folder.

Fix: Restructured the on-chain Folder for Efficiency

---

apps/frontend/app/page.tsx

- Resolved loading error on TopSellers component.

Fix: Resolved loading error for Top-Sellers component

---

on-chain/nftopia/src/events/nft_events.cairo
on-chain/nftopia/src/lib.cairo
on-chain/nftopia/src/modules/nft_contract.cairo
on-chain/nftopia/tests/test_nft_contract.cairo

Closes #46 
This PR implements a complete NFT contract module for the Nftopia platform, following the ERC721-like standard. The implementation provides core NFT functionality, including minting, transferring, and approval management, with proper security controls and event emission.
The implementation follows a modular approach with:  
- A clear public interface (INftContract) defining all available functions
- Internal helper functions for common operations
- Proper event emission for all state changes
- Comprehensive error handling with descriptive messages
- Zero address validation to prevent tokens from being sent to inaccessible addresses

Implement and test NFTModule Contract

---

apps/frontend/components/todays-picks.tsx

implemented today's market pick

---

apps/frontend/app/marketplace/page.tsx
apps/frontend/app/page.tsx
apps/frontend/components/CollectionCard.tsx

- Commented out yet to be created frontend components to avoid errors.

Fix: commented out yet to be created components to avoid errors

---

apps/backend/src/bids/bids.service.ts
apps/backend/src/events/dto/create-event.dto.ts
apps/backend/src/events/dto/update-event.dto.ts
apps/backend/src/events/entities/event.entity.ts
apps/backend/src/events/events.gateway.spec.ts
apps/backend/src/events/events.gateway.ts
apps/backend/src/events/events.module.ts
apps/backend/src/events/events.service.spec.ts
apps/backend/src/events/events.service.ts
package-lock.json
package.json

closes #97 
This PR introduces a dedicated **Events Module** to enable real-time auction and bid event handling via NestJS WebSocket Gateway. It provides live updates on auction state changes, bid placements, and active auctions broadcast, secured through JWT authentication and robust error handling.
---
- Validates JWT token on client connection.
- Associates connected sockets with authenticated users.
- Disconnects clients with invalid or expired tokens.
- `join_auction`: Allows clients to join specific auction rooms.
- `auction_state`: Broadcasts current auction data updates to subscribed users.
- `bid_history`: Provides full bid history for an auction on demand.
- `highest_bid`: Emits real-time leading bid updates to auction participants.
- `place_bid`: Validates and processes new …

Add# PR: Implement Real-Time Events Module for Auctions and Bids with Secure WebSocket Gateway 

---

apps/frontend/lib/file_drop_zone/FileDropZone.css
apps/frontend/lib/file_drop_zone/FileDropZone.tsx
apps/frontend/lib/file_drop_zone/useFileDrop.ts
apps/frontend/lib/index.ts
apps/frontend/lib/interfaces.ts

- Implemented a Reusable Drag-and-Drop Component `FileDropZone` in `apps/frontend/lib` directory with associated files.
close #127

feat: Implemented Custom Reusable Drag-and-Drop Component

---

apps/frontend/app/auth/register/page.tsx
apps/frontend/lib/config.ts

**Closes #124**
---
**Integrate User Registration Page (#124)**
Connect the frontend registration form to the backend authentication system using the `CreateUserDto` structure provided.
---
* **Updated API Configuration**: Changed the base URL from port `3001` to `9000` to match the backend server.
* **Aligned Request with `CreateUserDto`**:
* Removed the `isArtist` checkbox and its logic since the backend only accepts `walletAddress` and an optional `username`.
* Made sure `username` is only sent when not empty to comply with the `@IsOptional()` decorator in the DTO.
* **Enhanced Form UX**:
* Added loading indicators for wallet connection and registration process.
* Updated button text dynamically based on the current state.
* Added a character limit and improved placeholder text for the …

integrated frontend reg form to backend

---

nftopia-notification-service/package.json
nftopia-notification-service/pnpm-lock.yaml
nftopia-notification-service/src/app.ts
nftopia-notification-service/src/config/email.ts
nftopia-notification-service/src/controllers/email.controller.ts
nftopia-notification-service/src/middlewares/rateLimiter.ts
nftopia-notification-service/src/middlewares/validateRequest.ts
nftopia-notification-service/src/routes/email.routes.ts
nftopia-notification-service/src/routes/index.ts
nftopia-notification-service/src/services/emailService.ts
nftopia-notification-service/src/types/email.ts

All Acceptance Criteria Met:
1. SendGrid Node.js client integrated - Full API integration with proper error handling
2. Dynamic template support - All 4 email types (NFT purchase, bid alerts, announcements, password resets)
3. Email activity webhook handling - Comprehensive webhook processing for delivery tracking
4. Rate limiting protection - Per-endpoint rate limits to prevent abuse
5. Comprehensive error handling - Detailed logging and user-friendly error responses
close #165

feat: add SendGrid email provider close #165

---

on-chain/nftopia/src/modules/dynamic_metadata.cairo

feat: Implement Cairo On-Chain Contract for Dynamic Metadata Support or NFTs

---

apps/backend/src/auth/auth.controller.ts
apps/backend/src/auth/auth.module.ts
apps/backend/src/auth/auth.service.ts
apps/backend/src/users/users.service.ts
apps/backend/src/utils/verify-starknet-signature.ts
package.json
pnpm-lock.yaml

- Refactored verifySignature() Method in auth.service.ts to Enhance Nonce-Based Authentication.
close #130

feat: Refactored verifySignature() Method in auth.service.ts to Enhance Nonce-Based Authentication

---

nftopia_analytics/analytics/docs/schemas/visualization_schema.py
nftopia_analytics/analytics/serializers/__init__.py
nftopia_analytics/analytics/serializers/visualization_serializers.py
nftopia_analytics/analytics/services/data_processor.py
nftopia_analytics/analytics/services/plotly_generator.py
nftopia_analytics/analytics/tests/test_visualization.py
nftopia_analytics/analytics/urls.py
nftopia_analytics/analytics/views_dir/visualization_views.py
nftopia_analytics/nftopia_analytics/settings.py
nftopia_analytics/requirements.txt

- Implemented Plotly Visualization Endpoint for NFT Analytics
close #139

feat: Implemented Plotly Visualization Endpoint for NFT Analytics

---

nftopia-notification-service/package.json
nftopia-notification-service/pnpm-lock.yaml
nftopia-notification-service/src/app.ts
nftopia-notification-service/src/config/database.ts
nftopia-notification-service/src/controllers/notification.controller.ts
nftopia-notification-service/src/index.ts
nftopia-notification-service/src/routes/notification.routes.ts
nftopia-notification-service/src/services/email.service.ts
nftopia-notification-service/src/templates/assets/css/email-styles.css
nftopia-notification-service/src/templates/emails/purchase-confirmation/html.hbs
nftopia-notification-service/src/templates/partials/header.hbs
nftopia-notification-service/src/templates/partials/transaction-table.hbs
nftopia-notification-service/src/types/email.ts

- Designed HTML email tmeplates in `nftopia-notification-service`.
close #166

feat: Designed HTML email templates in nftopia-notification-service

---

on-chain/nftopia/src/events/royalty_events.cairo
on-chain/nftopia/src/lib.cairo
on-chain/nftopia/src/modules/marketplace/settlement.cairo
on-chain/nftopia/src/modules/nft_contract.cairo
on-chain/nftopia/src/modules/royalty/interfaces.cairo
on-chain/nftopia/src/modules/royalty/logic.cairo
on-chain/nftopia/src/modules/royalty_contract.cairo
on-chain/nftopia/src/modules/transaction.cairo
on-chain/nftopia/src/storage/royalty_storage.cairo
on-chain/nftopia/src/storage/transaction_storage.cairo
on-chain/nftopia/tests/test_royalty.cairo

- Wrote Cairo On-Chain Contract for Royalty Distribution for Secondary Sales.
close #184

feat: Wrote Cairo On-Chain Contract for Royalty Distribution for Secondary Sales

---

nftopia_analytics/analytics/admin.py
nftopia_analytics/analytics/tasks.py
nftopia_analytics/analytics/urls.py
nftopia_analytics/analytics/utils.py
nftopia_analytics/analytics/views.py
nftopia_analytics/docker-compose.yml
nftopia_analytics/nftopia_analytics/settings.py
nftopia_analytics/nftopia_analytics/urls.py
nftopia_analytics/requirements.txt

- Implemented IPFS Integration for metadata analysis in `nftopia-analytics`
close #175

feat: Implemented IPFS Integration for Metadata Analysis in nftopia-analytics

---

nftopia-payment-service/src/main/java/com/nftopia/paymentservice/config/SchedulerConfig.java
nftopia-payment-service/src/main/java/com/nftopia/paymentservice/dto/FraudCheckResult.java
nftopia-payment-service/src/main/java/com/nftopia/paymentservice/dto/FraudRiskLevel.java
nftopia-payment-service/src/main/java/com/nftopia/paymentservice/entity/Transaction.java
nftopia-payment-service/src/main/java/com/nftopia/paymentservice/entity/TransactionStatus.java
nftopia-payment-service/src/main/java/com/nftopia/paymentservice/repository/TransactionsRepository.java
nftopia-payment-service/src/main/java/com/nftopia/paymentservice/service/FraudBatchReviewScheduler.java
nftopia-payment-service/src/main/java/com/nftopia/paymentservice/service/FraudCheckService.java
nftopia-payment-service/src/main/java/com/nftopia/paymentservice/service/FraudRulesEngine.java
nftopia-payment-service/src/main/java/com/nftopia/paymentservice/service/TransactionCreatedEvent.java
nftopia-payment-service/src/main/java/com/nftopia/paymentservice/service/TransactionEventListener.java
nftopia-payment-service/src/main/java/com/nftopia/paymentservice/service/metrics/FraudMetricsService.java
nftopia-payment-service/src/test/java/com/nftopia/paymentservice/FraudRulesEngineTest.java

feat: Implement Transaction Fraud Check Service

---

on-chain/nftopia/.tool-versions
on-chain/nftopia/src/modules/access_control.cairo
on-chain/nftopia/src/modules/nft_contract.cairo

This PR introduces a comprehensive Role-Based Access Control (RBAC) system for  smart contracts, providing secure and flexible role management with multi-signature admin proposals and timelock mechanisms.
- **Four distinct roles**: Admin, Moderator, Treasury, and Upgrade roles
- **Flexible role assignment**: Support for individual and batch role operations
- **Role expiry system**: Configurable expiration timestamps for temporary permissions
- **Self-renunciation**: Users can voluntarily renounce their own roles
- **Proposal-based admin changes**: Admin role modifications require proposal creation
- **Multi-admin approval**: Configurable approval threshold for admin role changes
- **Timelock mechanism**: 24-hour delay after final approval before execution
- **Proposal tracking**: Complete …

Feat: Implement RBAC System for admin/moderator functions
